version: "3.8"

services:
  mysql:
    container_name: tt_mysql
    hostname: mysql
    image: mysql:8.0.27
    restart: on-failure
    ports:
      - 35001:3306/tcp
    volumes:
      - ./sql-script:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
      - ./dump:/home
    environment:
      MYSQL_DATABASE: '${APP_DATABASE_NAME}'
      MYSQL_PASSWORD: '${APP_DATABASE_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${APP_DATABASE_PASSWORD}'
      MYSQL_USER: '${APP_DATABASE_USER}'
    networks:
      - 'tt'

  php:
    container_name: tt_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    environment:
      APP_HOST: '${APP_HOST}'
      DB_NAME: '${APP_DATABASE_NAME}'
      DB_USER: '${APP_DATABASE_USER}'
      DB_PASSWORD: '${APP_DATABASE_PASSWORD}'
      DB_HOST: '${APP_DATABASE_HOST}'
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    networks:
      - 'global'
      - 'tt'

  nginx:
    container_name: tt_nginx
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - 'global'
      - 'tt'

networks:
  global:
    name: 'global'
    external: true
  tt: